version: '3.7'
services:
  redis:
    image: redis:alpine
    restart: on-failure
    expose:
      - 6979
    healthcheck:
      test: [ "CMD", "redis-cli", "-h", "localhost", "ping" ]
      interval: 1m
      timeout: 5s
      retries: 2

  backend:
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    env_file: .env
    stdin_open: true
    tty: true
    expose:
      - 8080
    ports:
      - "8080:8080"
    volumes:
      - .:/project
    depends_on:
      - redis
      - nginx
    command: uvicorn main.asgi:django_asgi_app --host 0.0.0.0 --port 8080 --ws auto

  nginx:
    restart: always
    image: library/nginx:1.9.0
    expose:
      - 8081
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
      - ./docker/logs/nginx:/var/log/nginx
      - ./backend:/backend

